name: deploy infra & apps

on:
  push:
    branches:
     - main
     
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: authenticate to gcp
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service-account-key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: my-first-project-85838
          
        

      - name: terraform init
        working-directory: /terraform
        run: terraform init
      
      
      - name: terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
      
      - name: build image via gcp
        run: |
          gcloud builds submit --tag gcr.io/my-first-project-85838/app_bucket.py
          gcloud run deploy my-first-app --image gcr.io/my-first-project-85838/my-first-app --platform managed --region us-central1 --allow-unauthenticated
        
      